// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hutmrnnfwxzflftwvmha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0b3N6aWJ2cHpuaXFzdGpqc2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDA5NTksImV4cCI6MjA2ODcxNjk1OX0.57tOILeYME3iLAZpvQWHEu1wm9uxFbw8RWO95MgPY8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});