// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hutmrnnfwxzflftwvmha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dG1ybm5md3h6ZmxmdHd2bWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Njg4NjUsImV4cCI6MjA3MDQ0NDg2NX0.y9hSsY3-371T1bVk7TDy3JQZpAb9SWaeoP-Nw-OUIYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});